package io.github.blyznytsiaorg.bibernate.annotation;

/**
 * Enumeration representing different strategies for generating values for annotated fields marked with
 * {@link io.github.blyznytsiaorg.bibernate.annotation.GeneratedValue}.
 * <p>
 * The available generation strategies are:
 * - {@link GenerationType#NONE}: No generation strategy is applied.
 * - {@link GenerationType#SEQUENCE}: Values are generated using a sequence.
 * - {@link GenerationType#IDENTITY}: Values are generated by the database upon insertion.
 *
 * @author Blyzhnytsia Team
 * @since 1.0
 */
public enum GenerationType {
    /**
     * No generation strategy is applied.
     */
    NONE,

    /**
     * Values are generated using a sequence.
     */
    SEQUENCE,

    /**
     * Values are generated by the database upon insertion.
     */
    IDENTITY
}
