package io.github.blyznytsiaorg.bibernate.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import static io.github.blyznytsiaorg.bibernate.annotation.GenerationType.IDENTITY;

/**
 * Marks a field as being generated by the database upon insertion. This annotation is typically applied to a field
 * within a Java class that represents an entity in a data store. It allows the specification of a generation strategy
 * for the annotated field, indicating how the database generates the values for this field.
 * <p>
 * The default generation strategy is {@link GenerationType#IDENTITY}.
 *
 * @author Blyzhnytsia Team
 * @since 1.0
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface GeneratedValue {
    /**
     * Specifies the generation strategy for the annotated field. The default is {@link GenerationType#IDENTITY}.
     *
     * @return The generation strategy for the annotated field.
     */
    GenerationType strategy() default IDENTITY;

    /**
     * Specifies the name of the generator to use (if applicable). The default is an empty string.
     *
     * @return The name of the generator.
     */
    String generator() default "";
}
